### ISSUE TITLE
can you help

### ISSUE THREAD

**Issue by jamiemc71** [BryceCanyonCounty/bcc-boats#13]
hey wonder if you could help me, this script was running perfectly fine for a week or so and todays its just started coming up this error, can ou help please

![error](https://github.com/BryceCanyonCounty/bcc-boats/assets/103319860/c0f9a825-459c-4aec-bf8c-88024672c565)

**Comment by jamiemc71** [comment]
is there any light to share on this?

**Comment by JusCampin** [comment]
I haven't seen this error in my testing nor had any other reports of it. The line called out in the error is trying to get your used character while selling a boat. 

Since I can't reproduce the error the only thing I can recommend is updating your vorp server files and trying a fresh download of boats.

**Comment by whatcorey** [comment]
I'm having the same issue. Though I haven't created a character yet, could that be the issue? I just made my server today but haven't played on it
